AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
Rails:
  Enabled: false

AndOr:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundMethodBody:
  Enabled: false

EmptyLinesAroundBlockBody:
  Enabled: false

EndAlignment:
  EnforcedStyleAlignWith: variable

LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'spec/database/**/*'

SpaceAroundEqualsInParameterDefault:
  Enabled: false

TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true

Metrics/ClassLength:
  Max: 120

# Changes from template

Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/AbcSize:
  Max: 30

Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
